const data = [
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Service Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Inosoft Bootcamp",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "In-Progress",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Service Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Draft",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Logistic Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Inosoft Bootcamp",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice data",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice new",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice data",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice new",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Completed",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Service Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Inosoft Bootcamp",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Completed",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Logistic Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Inosoft Bootcamp",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 3",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 4",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Completed",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Logistic Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Completed",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Service Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Inosoft Bootcamp",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "In-Progress",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Service Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Draft",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Service Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "In-Progress",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Logistic Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Inosoft Bootcamp",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Completed",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Service Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 3",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Completed",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Logistic Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Draft",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Logistic Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "In-Progress",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Logistic Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Inosoft Bootcamp",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "In-Progress",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Logistic Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "In-Progress",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Service Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "In-Progress",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Service Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Inosoft Bootcamp",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "In-Progress",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Service Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Draft",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Service Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Draft",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Logistic Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Cancelled",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Logistic Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Inosoft Bootcamp",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Cancelled",
    },
    {
        instruction_id: "LI-2023-0082",
        instruction_type: "Logistic Instruction",
        date_issued: "2023-09-12",
        assigned_vendor: "Semen Gresik",
        vendor_address: "Gresik 2",
        attention_of: "Asep Nurdadang",
        quotation_number: 72591,
        invoice_to: "FBI",
        customer_contact: "APUNK",
        customer_PO_number: "po1",
        cost_detail: [
            {
                cost_description: "cost pertama",
                quantity: 2,
                unit_of_measurement: "PCS",
                unit_price: 20,
                GST_percentage: 23,
                currency: "USD",
                vat_amount: 8.55,
                sub_total: 40,
                total: 48.55,
                charge_to: "APUNK",
            },
        ],
        attachment: "file",
        notes: "lorem ipsum",
        transaction_no: "TRF-2023-5102",
        invoices: [
            {
                invoice_number: "invoice 1",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
            {
                invoice_number: "invoice 2",
                invoice_attachment: "<file>",
                invoice_supporting_document: "<file>",
            },
        ],
        termination: [
            {
                termination_reason: null,
                attachment: "<file>",
            },
        ],
        instruction_status: "Cancelled",
    },
];

export default data;
